name = "SymbolicNumericIntegration"
uuid = "78aadeae-fbc0-11eb-17b6-c7ec0477ba9e"
authors = ["Shahriar Iravanian <siravan@svtsim.com>"]
version = "1.7.0"

[deps]
DataDrivenDiffEq = "2445eb08-9709-466a-b3fc-47e12bd697a2"
DataDrivenSparse = "5b588203-7d8b-4fab-a537-c31a7f73f46b"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
DataDrivenDiffEq = "1.5"
DataDrivenSparse = "0.1.2"
DataStructures = "0.18.13"
LinearAlgebra = "<0.0.1, 1"
SpecialFunctions = "2.1"
Statistics = "<0.0.1, 1"
SymbolicUtils = "2, 3"
Symbolics = "5.31, 6"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
